### ISSUE TITLE
Project Road Map

### ISSUE THREAD

**Issue by thtauhid** [thtauhid/terminal-portfolio#65]
Almost all the features are in place. 
Now we need to decide the future of this project. 

Possible futures-
**Project is kept in it's present state.** 
- Users can clone the repo
- Add their own details in data.json
- Host on their own

Or we can move in this direction-
**SaaS Model** (Suggest me better name)
- Users can come to this repo
- Submit their basic details
- They will get a terminal styled portfolio with link
- They can share the link with their friends

I really like the [BioDrop](https://github.com/EddieHubCommunity/BioDrop/) project. This model is similar to BioDrop. 

---
Join our [Discord server](https://discord.gg/3jvahVGKfa) to discuss ideas, ask questions, and collaborate with others.

**Comment by LinhNguyenLe2109** [comment]
I think in terms of functionality, its better to do it as a web instead of a downloadable repo, this way we can reach out to may more people, even those that are not familiar with code. However, I need to understand the scope of this project more

General idea should be open the site --> it walks you through a list of basic questions --> it display what you entered --> you generate a link and send it to another person --> that person can see what you enter

Still, there are many unique thing we can do with this:
- Login/logout (have to implement DB)
- better, more modern UI
- Abilities to customize the way it display data

**Comment by thtauhid** [comment]
Project roadmap to be designed based on https://github.com/thtauhid/terminal-portfolio/blob/main/ABOUT.md
